import 'package:quiz_app/service/english.dart';

const Map<String, String> tigrinya = {
  // Log In Screen
  'LOGIN': 'እቶ',
  'Enter email': 'ኢመይል ኣእቱ',
  'Login': 'እቶ',
  'Remember me': 'ዘክርኒ።',
  'Enter password': 'ምልክት ቃል ኣእትዉ',
  'Don`t have an account ?': 'ኣካውንት የብልካን።',
  'Sign up': 'ተመዝገቡ።',
  "select language": "ቋንቋ ምረጽ",
  'Password canot be empty': 'ምልክት ቃል ባዶ ክኸውን ኣይክእልን እዩ።',
  'Email canot be empty': 'ኢመይል ባዶ ክኸውን ኣይክእልን እዩ።',
  'Create_account': 'ሕሳብ ፍጠር',
//'create_account':'ሕሳብ ፍጠር',
  "select_category": "ምድብ ምረጽ",
  "front_end": "ናይ ቅድሚት ፍጻሜ",
  "cloud_service": "ኣገልግሎት ደበና",
  "back_end": "ናይ መወዳእታ ፍጻሜ",
  "select_type": "ዓይነት ምረጽ",
  "practice_test": "መለማመዲ ፈተና",
  "evalution_exam": "መርመራ ገምጋም",
  'your_score': 'ነጥብካ',
  'review': 'ድግማ',
  'done': 'እተገብረ/እተሰርሐ',

  'edit_profile': 'ቅርጺ ኣዳሉ',
  'dashboard': 'መቆጻጸሪ/መዐቀኒ',
  'users': 'ተጠቀምቲ',
  'active': 'ንጡፍ ',
  'blocked': 'ዓገተ',
  //'enter_email': 'ኢመይል ኣእቱ',

  //'enter Password': '',
  //'Password canot be empty': 'ምልክት ቃል ባዶ ክኸውን ኣይክእልን እዩ።',
  // 'Email canot be empty': 'ኢመይል ባዶ ክኸውን ኣይክእልን እዩ።',
  'Exam information': 'ሓበሬታ ፈተና',
  'OK': 'እሺ',
  'hello you have 2 and half hours time to  finish the exam. are you ready to take exam ?':
      'ሰላም ፈተና ንምውዳእ ናይ 2 ሰዓትን ፈረቓን ግዜ ኣለኩም። ፈተና ክትወስድ ድሉው ዲኻ ?',
  'No Questions Available': 'ዝኾነ ሕቶ የለን',
  'Please practice or choose other languages to test on.':
      'በጃኹም ካልእ ቋንቋታት ክትፍትነሎም ክትለማመዱ ወይ ምረጽ።',
  'Account': 'ኣካውንት',
  'Profile': 'መግለፂ',
  'Personal': 'ውልቃዊ',
  'View and update profile': 'ፕሮፋይል ርአን ኣዘምንን።',
  'Admin Settings': 'ናይ ኣድሚን ቅጥዕታት',
  'Dashboard': 'ዳሽቦርድ',
  'Statistics': 'ስታቲስቲክስ',
  'Other': 'ካልእ',
  'My Scores': 'ናተይ ነጥብታት',
  'Achievements': 'ዓወታት',
  'Recommendations': 'ለበዋታት',
  'kabbee recommend you to Visit': 'ካቢ ክትበጽሑ ይመኽሩኹም',
  'Logging Out': 'ምውጻእ',
  'Are You sure you want to log out?': 'ርግጸኛ ዲኻ ክትወጽእ ትደሊ?',
  'yes': 'እወ',
  'no': 'አይኮንን',
  'Log Out': 'ውጽእ',
  'Exit from the application': 'ካብቲ መተግበሪ ውጻእ',
  'Edit Profile': 'ፕሮፋይል ኣርትዕ',
  'First_Name': 'ናይ መጀመርታ ሽም',
  'Last Name': 'ናይ መወዳእታ ሽም',
  'Password': 'መሕለፊ ቓል',
  'UPDATE': 'ኣዘምን',
  'Gender': 'ፆታ',
  'male': 'ተባዕታይ',
  'female': 'ኣንስተይቲ',
  'My_Scores': 'ናተይ_ነጥብታት',
  'Your score list is Empty !': 'ዝርዝር ነጥብታትካ ባዶ እዩ !',
  'Do Some Exams and check your results here.': 'ገለ ፈተናታት ግበር እሞ ውጽኢትካ ኣብዚ ርአ።',
  'percentage': 'ሚእታዊት ምዃኑ’ዩ።',
  'PRACTICE': 'ትግበራ',
  // '' : '',
  // '' : '',
  // '' : '',
  // '' : '',
  // '' : '',
  // '' : '',
  // '' : '',
// //
};
