import 'package:quiz_app/service/english.dart';

const Map<String, String> tigrinya = {
  // Log In Screen
  'LOGIN': 'እቶ',
  'Enter email': 'ኢመይል ኣእቱ',
  'Login': 'እቶ',
  'Remember me': 'ዘክርኒ።',
  'Enter password': 'ምልክት ቃል ኣእትዉ',
  'Don`t have an account ?': 'ኣካውንት የብልካን።',
  'Sign up': 'ተመዝገቡ።',
  "Select language": "ቋንቋ ምረጽ",
  'Password canot be empty': 'ምልክት ቃል ባዶ ክኸውን ኣይክእልን እዩ።',
  'Email canot be empty': 'ኢመይል ባዶ ክኸውን ኣይክእልን እዩ።',
  'Create account': 'ሕሳብ ፍጠር',
  //Sign in
  'Email': 'ኢመይል',
  'Full Name': 'ምሉእ ስም',
  'please tell us more about you': 'በጃኻ ብዛዕባኻ ዝያዳ ንገረና።',
  'First Name cannot be empty': 'ቀዳማይ ስም ባዶ ክኸውን ኣይክእልን እዩ።',
  'Enter First Name': 'ቀዳማይ ስም ኣእቱ',
  'enter_new_password': 'ሓድሽ ምስጢር ቃል የአቱ',
  'Last Name cannot be empty': 'መወዳእታ ስም ባዶ ክኸውን ኣይክእልን እዩ።',
  'Enter Last Name': 'መወዳእታ ስም ኣእቱ',
  'change_avatar': 'ምስሊ ቀይር',
  'Upload': 'ጸዓን',
  'Next': 'ቀጻሊ',

  // Category screen\
  "Select Category": "ምድብ ምረጽ",
  //languages
  "Front-End": "ፍሮንት-ኤንድ",
  "Front end": "ፍሮንት-ኤንድ",
  "Cloud-Service": "ክላውድ ሰርቪስ",
  "Back-End": "ባክ-ኤንድ",
  "Back end": "ባክ-ኤንድ",
  'BACK_END': 'ባክ-ኤንድ',
  'Atlas_Cloud': 'ኣትላስ ክላውድ',
  'MongoDB': 'ሞንጎዲቢ',
  'javascript': 'ጃቫስክሪፕት',
  'FRONT-END': 'ፍሮንት-ኤንድ',
  'Flutter': 'ፍላተር',
  'Dart': 'ዳርት',
  'CLOUD_SERVICES': 'ክላውድ ሰርቪስ',
  'Cloud services': 'ክላውድ ሰርቪስ',
  'Machine_Learning': 'ማሽን ለርኒንግ',
  'JAVASCRIPT': 'ጃቫስክሪፕት',
  'HTML_CSS': 'ኤችቲኤምኤል_ሲኤስኤስ',
  'HTML CSS': 'ኤችቲኤምኤል_ሲኤስኤስ',
  'DART': 'ዳርት',
  'FLUTTER': 'ፍላተር',
  'MACHINE_LEARNING'
      '': 'ማሽን ለርኒንግ',
  'MACHINE LEARNING': 'ማሽን ለርኒንግ',
  'CLOUD_COMPUTING': 'ክላውድ ኮምፒዩቲንግ',
  'CLOUD COMPUTING': 'ክላውድ ኮምፒዩቲንግ',
  'ANALYTICS': 'ኣናልይቲክስ',
  'MONGODB': 'ሞንጎዲቢ',
  'ATLAS_CLOUD': 'ኣትላስ ክላውድ',
  'ATLAS CLOUD': 'ኣትላስ ክላውድ',
  //select language
  'Select Language': 'ቋንቋ ምረጽ',
  'Select Type': 'ዓይነት ምረጽ',
  'Practice Test': 'ናይ ልምምድ ፈተና።',

  "Evalution Exam": "ናይ ገምጋም ፈተና",
  'your_score': 'ነጥብካ',
  'REVIEW': 'ድግማ',
  'done': 'እተገብረ/እተሰርሐ',
  'CANCEL': 'ሰርዝ',
  'CONTINUE': 'ቀፃሊ',
  'DONE': 'ምውዳእ',
  'hello you have unanswered question . Do you want go back and check or continue to score page ?':
      'ሰላም ዘይተመለሰ ሕቶ ኣለኩም . ንድሕሪት ተመሊስካ ገጽ ነጥቢ ክትምርምር ወይ ክትቅጽል ትደሊ ዲኻ ?',
  'Notice': 'ኣፍልጦ',
  'navigate': 'ምጉዓዝ',
  'hello you can\'t back during exam starts':
      'ሰላም ፈተና ኣብ ዝጅምረሉ እዋን ክትምለስ ኣይትኽእልን ኢኻ።',
  'edit_profile': 'ፕሮፋይል ኣርትዕ',
  'dashboard': 'መቆጻጸሪ/መዐቀኒ',
  'users': 'ተጠቀምቲ',
  'ACTIVE': 'ንጡፍ ',
  'blocked': 'ዓገተ',

  'Exam information': 'ሓበሬታ ፈተና',
  'OK': 'እወ',

  'hello you have 2 and half hours time to  finish the exam. are you ready to take exam ?':
      'ሰላም ፈተና ንምውዳእ ናይ 2 ሰዓትን ፈረቓን ግዜ ኣለኩም። ፈተና ክትወስድ ድሉው ዲኻ ?',
  'No Questions Available': 'ዝኾነ ሕቶ የለን',
  'Please practice or choose other languages to test on.':
      'በጃኹም ካልእ ቋንቋታት ክትፍትነሎም ክትለማመዱ ወይ ምረጽ።',
  'Account': 'ኣካውንት',
  'Profile': 'ፕሮፋይል',
  'Personal': 'ውልቃዊ',
  'View and update profile': 'ፕሮፋይል ርአን ኣማዕብልን',
  'Admin Settings': 'ናይ ኣድሚን ቅጥዕታት',
  'Dashboard': 'ዳሽቦርድ',
  'Statistics': 'ስታቲስቲክስ',
  'Other': 'ካልእ',
  'My Scores': 'ናተይ ነጥብታት',
  'Achievements': 'ዓወታት',
  'Recommendations': 'ለበዋታት',
  'kabbee recommend you to Visit': 'ካቢ ክትበጽሕዎ ይመኽረኩም',
  'Logging Out': 'ምውጻእ',
  'Are You sure you want to log out?': 'ርግጸኛ ዲኻ ክትወጽእ ትደሊ?',
  'Yes': 'እወ',
  'No': 'አይኮነን',
  'Log Out': 'ውጻአ',
  'Exit from the application': 'ካብቲ መተግበሪ ውጻእ',
  'Edit Profile': 'ፕሮፋይል ኣርትዕ',
  'First_Name': 'ናይ መጀመርታ ሽም',
  'Last Name': 'ናይ መወዳእታ ሽም',
  'Password': 'ምስጢር ቓል',
  'UPDATE': 'ኣማዕብል',
  'Gender': 'ጾታ',
  'Male': 'ተባዕታይ',
  'Female': 'ኣንስተይቲ',
  'My_Scores': 'ናተይ_ነጥብታት',
  'Your score list is Empty !': 'ዝርዝር ነጥብታትካ ባዶ እዩ !',
  'Do Some Exams and check your results here.': 'ገለ ፈተናታት ግበር እሞ ውጽኢትካ ኣብዚ ርአ።',
  'percentage': 'ሚእታዊት',
  'PRACTICE': 'ልምምድ',
  'Dark Mode': 'ጸሊም ትርኢት',
  'Change theme': 'ትርኢት ቀይር',
  'First Name': 'ናይ መጀመርታ ሽም',
  'Enter new password': 'ሓድሽ ምስጢር ቃል ኣእቱ',
  'Users': 'ተጠቀምቲ',
  'USERS': 'ተጠቀምቲ',
  'COURSES': 'ኮርሳት',
  'Courses': 'ኮርሳት',
  'TOTAL': 'ድምር',
  'CATEGORIES': 'ምድባት',
  'See active and blocked': 'ንጡፍን ዝተዓጽወን ርአ',
  'View and update courses': 'ኮርሳት ምርኣይን ምምዕባል',

  'BLOCKED': 'ተዓጽዩ ኣሎ።',
  'Users Not Found !': 'ተጠቀምቲ ኣይተረኽበን !',
  'All users are active': 'ኩሎም ተጠቀምቲ ንጡፋት እዮም።',
  'You need A valid email Address': 'ቅኑዕ ናይ ኢመይል ኣድራሻ የድልየካ ኣሎ',
  'please enter your password': 'በጃኹም ምስጢር ቃል ኣእትዉ',
  'Enter a Valid Password': 'ቅኑዕ ምስጢር ቃል ኣእቱ',
  'The Two password need to be  the same ': 'እቶም ክልተ ምስጢር ሓደ ዓይነት ክኾኑ ኣለዎም።',
  'Confirm Password': 'ምስጢር ቃል ኣረጋግጽ',
  '* Password have to have 6 or more in characters \n * At to have at least on UpperCase letter \n * At least one digit \n at least one special character  ':
      '* ምስጢር ቃል 6 ወይ ልዕሊኡ ፊደላት ክህልዎ ኣለዎ \n *  እንተወሓደ ኣብ ዓበይቲ ፊደላት ክህልዎ ኣለዎ \n * እንተወሓደ ሓደ ኣሃዝ \n እንተወሓደ ሓደ ፍሉይ ፊደል',
  'No internet': 'ኢንተርነት የለን',
  'Please check your internet connectivity': 'በጃኹም ናይ ኢንተርነት ምትእስሳርኩም መርምሩ።',
};
